// <auto-generated />
using System;
using CustomClothing.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomClothing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomClothing.model.ClothingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Куртки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Футболки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Штаны"
                        });
                });

            modelBuilder.Entity("CustomClothing.model.CompletedWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClothingCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClothingCategoryId");

                    b.ToTable("CompletedWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClothingCategoryId = 1,
                            Description = "Классическая куртка с ручной росписью на спине",
                            IsPublic = true,
                            Name = "Кожанка 'Old School'"
                        },
                        new
                        {
                            Id = 2,
                            ClothingCategoryId = 2,
                            Description = "Светящийся принт, оверсайз крой",
                            IsPublic = true,
                            Name = "Футболка 'Cyber-Punk'"
                        },
                        new
                        {
                            Id = 3,
                            ClothingCategoryId = 1,
                            Description = "Этот заказ не виден обычным пользователям",
                            IsPublic = false,
                            Name = "Секретный проект X"
                        });
                });

            modelBuilder.Entity("CustomClothing.model.DesignRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClothingCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClothingCategoryId");

                    b.ToTable("DesignRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClothingCategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Алексей",
                            CustomerPhone = "+79001112233",
                            DeliveryAddress = "ул. Ленина 1",
                            Description = "Хочу вышивку золотого дракона",
                            Status = 0,
                            Title = "Худи с драконом"
                        },
                        new
                        {
                            Id = 2,
                            ClothingCategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Алена",
                            CustomerPhone = "88005553535",
                            DeliveryAddress = "ул. Карла Маркса 2",
                            Description = "Нужны кастомные нашивки по бокам",
                            Status = 0,
                            Title = "Шорты для бега"
                        });
                });

            modelBuilder.Entity("CustomClothing.model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedWorkId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedWorkId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CustomClothing.model.CompletedWork", b =>
                {
                    b.HasOne("CustomClothing.model.ClothingCategory", "Category")
                        .WithMany("CompletedWorks")
                        .HasForeignKey("ClothingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CustomClothing.model.DesignRequest", b =>
                {
                    b.HasOne("CustomClothing.model.ClothingCategory", "Category")
                        .WithMany()
                        .HasForeignKey("ClothingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CustomClothing.model.Order", b =>
                {
                    b.HasOne("CustomClothing.model.CompletedWork", "CompletedWork")
                        .WithMany()
                        .HasForeignKey("CompletedWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedWork");
                });

            modelBuilder.Entity("CustomClothing.model.ClothingCategory", b =>
                {
                    b.Navigation("CompletedWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
